// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qTHg-k0lkHRxYzoS7KnIBwvdxUstvU8',
    appId: '1:843028441897:web:df0ee1380243a85a9ea538',
    messagingSenderId: '843028441897',
    projectId: 'hayyarabic',
    authDomain: 'hayyarabic.firebaseapp.com',
    storageBucket: 'hayyarabic.firebasestorage.app',
    measurementId: 'G-HEBP5L46GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphpUgk5Rb2_2wfLvA3yH7FWE42DyFX9U',
    appId: '1:843028441897:android:f7cee3ebf7ece5329ea538',
    messagingSenderId: '843028441897',
    projectId: 'hayyarabic',
    storageBucket: 'hayyarabic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYxQu4wL6QJ38Kkg4-C2Z3kn3EQdhYvU',
    appId: '1:843028441897:ios:fef1c1371b7ff0469ea538',
    messagingSenderId: '843028441897',
    projectId: 'hayyarabic',
    storageBucket: 'hayyarabic.firebasestorage.app',
    iosBundleId: 'com.example.fpimk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKYxQu4wL6QJ38Kkg4-C2Z3kn3EQdhYvU',
    appId: '1:843028441897:ios:fef1c1371b7ff0469ea538',
    messagingSenderId: '843028441897',
    projectId: 'hayyarabic',
    storageBucket: 'hayyarabic.firebasestorage.app',
    iosBundleId: 'com.example.fpimk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-qTHg-k0lkHRxYzoS7KnIBwvdxUstvU8',
    appId: '1:843028441897:web:89ad521352f521039ea538',
    messagingSenderId: '843028441897',
    projectId: 'hayyarabic',
    authDomain: 'hayyarabic.firebaseapp.com',
    storageBucket: 'hayyarabic.firebasestorage.app',
    measurementId: 'G-JEN83WFBL1',
  );
}
